### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tebriz159** [Michaelpalacce/Server#1]
Hello mate, I wanted to contribute on your new project and I made a logo. If you like to use it I will send you original files. I am waiting for your answer. Here is it:

![server logo](https://user-images.githubusercontent.com/31902754/41318099-1a0347ce-6e4c-11e8-9461-cb05eaf86492.png)

Or

![or](https://user-images.githubusercontent.com/31902754/41318129-32e9a90e-6e4c-11e8-9509-ca662305b1ee.png)

**Comment by Michaelpalacce** [comment]
Hey! I haven't gotten into the front end of the application yet but if you want you can submit a pull request with the resources or you can put the logo wherever you want in the page! Feel free I'll review the pull request asap

**Comment by tebriz159** [comment]
Thank you for using it. Here's all files about logo https://drive.google.com/open?id=1fOsfy2Xw0dZqKW-_nQZlnyZkBZsXKSVx
